### ISSUE TITLE
Update User Guide v2.1 with Checklist

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#96]
Comply with **CS2101** Checklist:

* Add Introduction to concepts?
* Add label for images
* Explain bullet points used at each command
* Add numberings for section headers
* Add clear instructional steps for each command
* Add diagrams/formatting/colours/arrows/tips for each command
* Add glossary (optional)

[10.2 UGDG checklists for Peer Review.pdf](https://github.com/AY2021S1-CS2113T-W13-3/tp/files/5438341/10.2.UGDG.checklists.for.Peer.Review.pdf)

Add new features/Update existing features:

* Storage?
* `RlcTemplate`?

**Comment by sevenseasofbri** [comment]
### CheckList
- [x] Add Introduction to concepts.
- [x] Add label for images.
- [x] Explain bullet points used at each command.
- [x] Add numberings for section headers.
- [x] Add clear instructional steps for each command.
- [x] Add diagrams/formatting/colours/arrows/tips for each command.
- [x] Add glossary (optional).

**Comment by hughjazzman** [comment]
Images to be added assignment

| Section | Assigned |
|-|-|
|Tutorial | @oasisbeatle |
|Template | @dorianfong98  |
|Set | @PraveenElango |
|Add | @hughjazzman |
|Calc | @sevenseasofbri |
|Summary | @hughjazzman |
|Bye| @sevenseasofbri |
