### ISSUE TITLE
Prepare Demo

### ISSUE THREAD

**Issue by hughjazzman** [AY2021S1-CS2113T-W13-3/tp#97]
For CS2101 Demo:

* Record short (<=20s) video to showcase product

[Group 3_OP 2 Consultation.pdf](https://github.com/AY2021S1-CS2113T-W13-3/tp/files/5438364/Group.3_OP.2.Consultation.pdf)

For CS2113T Demo:

* Record a demo of all the product features, in a reasonable order.

https://nus-cs2113-ay2021s1.github.io/website/schedule/week13/project.html#2-submit-the-demo-video-wed-nov-11th-2359

**Comment by hughjazzman** [comment]
@PraveenElango will do this Introduce section
**Introduce**: (one or 2 members can do this)

- What is your product about?
- Who is your target user?
- What is the problem statement you are addressing?

**Details**: (ideally everyone takes part in the demo)

- As a courtesy, introduce yourself (though if you miss, it is OK!)
- Which part of the problem is your feature/command addressing?
- How to use your feature via what commands?
- If commands have different variations, show a few variations, no need to show everything

[demo.pdf](https://github.com/AY2021S1-CS2113T-W13-3/tp/files/5502454/demo.pdf)

**Comment by sevenseasofbri** [comment]
### General Structure of Video -> UG

Intro -> General -> Circuit -> Boolean -> End

Ideally, these are the parts each of us could do:
* [x] Prepare intro part of the video @PraveenElango 
* [x] Summary and Bye Command Demo and Voiceover
* [x] Tutorial Command Demo and Voiceover @oasisbeatle 
* [x] Template Command Demo and Voiceover @dorianfong98 
* [x] Set Command Demo and Voiceover @PraveenElango 
* [x] Add Command Demo and Voiceover @hughjazzman 
* [x] Calc Command Demo and Voiceover @sevenseasofbri 
* [x] Any notable features at implementation level? or at documentation level? or feature level?

Preferably go through most permutations of possible commands and also include erroneous commands too. Try and keep the parts < 3.5 mins long
